### ISSUE TITLE
Kubernetes liveness and readiness probs with basic auth

### ISSUE THREAD

**Issue by MetalRex101** [gomods/athens-charts#26]
**Describe the bug**
When basic auth is turned on, kubernetes liveness and readiness probs are always failed with 401 http error, because liveness and readiness url are hardcoded in deployment with out any basic auth support.

**Error Message**
Pod goes to crush loop because of 401 http error.

**To Reproduce**
Set up basic auth, deploy server to kubernetes cluster.

**Expected behavior**
Readiness and liveness probs use basic auth credentials, provided in secrets.

**Environment (please complete the following information):**
 - Google kubernetes cluster
 - Proxy version: Helm - athens-proxy-0.4.3, APP - 0.7.0
 - Storage: GCS

**Comment by DrPsychick** [comment]
The referenced changes are live and probe paths excluded from basicAuth:
https://github.com/gomods/athens/blob/43ee4259e31561f7167d7aadbd80d9a2d7884fd8/cmd/proxy/actions/basicauth.go#L12
