### ISSUE TITLE
Support Recommended K8s Labels

### ISSUE THREAD

**Issue by alex-bezek** [gomods/athens-charts#44]
Currently, this helm chart uses the label `app` across resources such as [here](https://github.com/gomods/athens-charts/blob/main/charts/athens-proxy/templates/deployment.yaml#L6C37-L6C37). This works great for the most part, except internally, we have tooling that relies on the Kubernetes [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels), specifically `app.kubernetes.io/instance`. 

Would you be open to accepting a contribution that adds this label, or alternatively, add a helm value for passing additional common labels similar to how other helm charts work https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml#L66

Thank you for the great app and chart, if you are open to either of these options, let me know and I can make a PR!

**Comment by DrPsychick** [comment]
Hey @alex-bezek, that is an absolute reasonable request, thanks for taking the time to propose it.
Please do open a PR and I will review it as soon as I can.

**Comment by alex-bezek** [comment]
@DrPsychick I've opened a PR that adds in the new labels and allows users to pass in additional labels as well https://github.com/gomods/athens-charts/pull/45
Thanks!
