### ISSUE TITLE
Impossible to disable ServiceAccount

### ISSUE THREAD

**Issue by mxk** [gomods/athens-charts#69]
If `serviceAccount.create` is set to `false`, the deployment fails because the Pod spec still ends up with a `serviceAccount: {{ template "fullname" . }}` attribute. That should probably be conditional.

**Comment by zoomoid** [comment]
For pre-provisioned service accounts, this breaks the chart's functionality of adding service accounts to the deployment entirely, because in that case we don't want it to create a Service Account but also want to template in the name
